name: Production Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Initialise Environment
        run: ./init.sh master ${{ secrets.DEPLOYMENT_USERNAME }} ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Inject env vars
        run: |
          echo VITE_DISCORD_CLIENT_ID=${{ secrets.DISCORD_BOT_ID }} > .env

      - name: Build Application
        run: npm run build

      - name: Create tarball
        run: tar -czf dist.tar.gz ./dist

      - name: Copy build to remote
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./dist.tar.gz home-server@ironicpickle.uk:/home/home-server/claudia/production/claudia-client

      - name: Deploy to remote
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null home-server@ironicpickle.uk "\
            cd /home/home-server/claudia/production/claudia-client
            rm ./dist -rf && \
            tar -xzf dist.tar.gz && \
            rm dist.tar.gz"
